Avoid test certs generation if test namespace not set
When environment variable `FLEET_E2E_NS` is not set, certificates would
be generated with an unusable SAN DNS name, which would ultimately lead
to OCI test failures. Therefore, the certificates generation script now
exits in such cases.

diff --git a/dev/create-zot-certs b/dev/create-zot-certs
--- a/dev/create-zot-certs
+++ b/dev/create-zot-certs
@@ -20,6 +20,11 @@ must_create_certs ()
     return $?
 }
 
+if [ -z $FLEET_E2E_NS ]; then
+    echo "Error: env var FLEET_E2E_NS is not set. Exiting."
+    exit 1
+fi
+
 must_create_certs
 if [ $? -eq 1 ]; then
     # generate private key for CA
